.sonarcloud.properties, .travis.yml, sonar-project.properties
=> onboard placementrule on sonarCloud

.travis.yml
=> let sonarCloud run when the PR is merged to master

.travis.yml, Makefile
https://github.com/open-cluster-management/backlog/issues/1060
Fixing above,
=> tagging image for community operator

README.md
=> get sonarCloud code coverage badge

cmd/manager/exec/manager.go, pkg/controller/placementrule/placementrule_controller.go, pkg/utils/placement.go
https://github.com/open-cluster-management/backlog/issues/1025
=> watch Clusters only when the ACM Cluster API service is ready

cmd/manager/exec/manager.go, pkg/utils/placement.go
=> func DetectClusterRegistry to package utils

.travis.yml, pkg/utils/kubernetes.go
https://github.com/open-cluster-management/backlog/issues/979  
https://github.com/open-cluster-management/backlog/issues/844
=> security scan fixes

pkg/utils/kubernetes.go
=> security fix

pkg/apis/apps/v1/placementrule_types.go, pkg/controller/placementrule/placement.go, pkg/controller/placementrule/placementrule_controller.go, pkg/utils/auth.go
https://github.com/open-cluster-management/backlog/issues/1467
=> filter clusters by user/group annotations

build/Dockerfile
https://github.com/open-cluster-management/backlog/issues/3000
=> update ubi image

pkg/utils/kubernetes.go, pkg/utils/placement.go
=> clusters in terminating process will not be selected

build/Dockerfile
https://github.com/open-cluster-management/backlog/issues/3109
=> update UBI image to the latest

pkg/apis/apps/v1/placementrule_types.go, pkg/utils/auth.go, pkg/utils/placement.go
https://github.com/open-cluster-management/backlog/issues/3671
=> Policy applied to managedcluster that user does not have access to

pkg/utils/cluster.go
https://github.com/open-cluster-management/backlog/issues/6158
=> reconcile placementrule when managedCluster is being detached

README.md, deploy/operator.yaml, deploy/role.yaml, deploy/role_binding.yaml, deploy/service_account.yaml, docs/deployment.md, docs/development.md
=> update community doc

README.md
=> fix link for readme

pkg/controller/argocdcluster/argocdcluster.go, pkg/controller/argocdcluster/argocdcluster_controller.go
=> avoid to watch KlusterletAddonConfig if the acm api server is not ready

pkg/utils/predicate_test.go, pkg/utils/utils_suite_test.go, pkg/utils/utils_test.go
=> append unit tests to utils package

pkg/controller/argocdcluster/argocd_controller_test.go, pkg/controller/argocdcluster/argocdcluster_controller.go
=> resolve argocd server pod deletion test failure due to slow travis env

pkg/controller/argocdcluster/argocdcluster_controller.go
https://github.com/open-cluster-management/backlog/issues/9154
=> get argocd server namespace by its service, which contains fixed labels

cmd/argocdcluster/exec/manager.go, go.mod, go.sum, pkg/controller/argocdcluster/argocd_controller_test.go, pkg/controller/argocdcluster/argocdcluster.go, pkg/controller/argocdcluster/argocdcluster_controller.go, pkg/controller/argocdcluster/argocdcluster_controller_suite_test.go
=> the endpoint-operator renamed to public repo klusterlet-addon-controller

Makefile.prow
=> fix prow build

Makefile, deploy/operator.yaml
=> use latest instead of community-latest

Makefile.prow, build/setup-tests.sh, build/test-package.sh, deploy/crds/apps.open-cluster-management.io_placementrules_crd.yaml, hack/test/crds/agent.open-cluster-management.io_klusterletaddonconfigs_crd.yaml, hack/test/crds/clusters.open-cluster-management.io_managedclusters.crd.yaml, pkg/utils/kubernetes.go
https://github.com/open-cluster-management/backlog/issues/10642
=> upgrade placementrule CRD to v1

examples/e2e_example/select_cluster_all_e2e.yaml, examples/e2e_example/select_cluster_by_label_e2e.yaml, examples/e2e_example/select_cluster_condition_all_avail_e2e.yaml
Add placement rules for end-to-end tests.
Signed-off-by: Philip Wu <phwu@redhat.com>
=> Add placement examples

pkg/controller/placementrule/placement.go, pkg/controller/placementrule/placementrule_controller_test.go
=> enable metric sorting

cmd/manager/exec/manager.go, pkg/controller/placementrule/placement.go, pkg/controller/placementrule/placementrule_controller.go, pkg/utils/auth.go, pkg/utils/placement.go
https://github.com/open-cluster-management/backlog/issues/12314
https://github.com/open-cluster-management/backlog/issues/12285
=> Placement performance enhacement

deploy/crds/apps.open-cluster-management.io_placementrules_crd.yaml, pkg/apis/apps/v1/placementrule_types.go
https://github.com/open-cluster-management/backlog/issues/8702
Signed-off-by: Philip Wu <phwu@redhat.com>
=> Change spec to required

pkg/controller/gitopscluster/gitopscluster_controller.go
Signed-off-by: Joshua Packer <jpacker@redhat.com>
* Adjust two of the configMap keys, found in further testing.
=> Fix ConfigMap keys

pkg/controller/gitopscluster/gitopscluster_controller.go, pkg/controller/gitopscluster/gitopscluster_controller_test.go
Signed-off-by: Roke Jung <roke@redhat.com>
=> placement needs to be in the same namespace

pkg/controller/gitopscluster/gitopscluster_controller.go
Signed-off-by: Roke Jung <roke@redhat.com>
https://github.com/open-cluster-management/backlog/issues/12996
When going through managed clusters to register, skip any unavailable managed cluster and continue copying secrets of available managed clusters.
=> skip unavailable managed clusters and continue

pkg/controller/gitopscluster/gitopscluster_controller.go, pkg/controller/gitopscluster/gitopscluster_controller_test.go
Signed-off-by: Roke Jung <roke@redhat.com>
https://github.com/open-cluster-management/backlog/issues/13790
The criteria that was used to verify the provided argocd namespace does not always work due to different ways to install ArgoCD.
=> fix argocd namespace verification

pkg/utils/auth.go
https://github.com/open-cluster-management/backlog/issues/14342
=> add new given cluster admin user for better placementRule performance

build/Dockerfile.prow, go.mod, go.sum
https://github.com/open-cluster-management/backlog/issues/15570
=> upgrade to go 1.17

Makefile, README.md, build/Dockerfile.prow
=> rename module name to stolostron

pkg/controller/placementrule/placementrule_controller.go
https://bugzilla.redhat.com/show_bug.cgi?id=2074156
=> 2.4: Retry err when placementrule status update fails
